name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi uvicorn pytest httpx pytest-cov

      - name: Run tests with coverage
        run: pytest --cov=src tests/

      - name: Build Docker Image
        run: docker build -t social-media-app .

      - name: Run Docker Container
        run: docker run -d -p 8000:8000 --name social-media-app social-media-app

      - name: Test API with httpx
        run: pytest tests/test_api.py

      - name: Stop and remove Docker container
        run: |
          docker stop social-media-app
          docker rm social-media-app
